export const PATHS = {
  public: {
    home: '/',
    booking: '/book/:slug/:code',
  },
  auth: {
    root: '/auth',
    login: '/auth/login',
    register: '/auth/register',
    confirmEmail: '/auth/confirm-email',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    adminInvitation: '/auth/admin-invitation',
    secretaryInvitation: '/auth/secretary-invitation',
    secretarySetup: '/auth/secretary-password-form',
  },
  dashboard: {
    overview: '/dashboard',
    adminOverview: '/dashboard/admin',
    adminOwners: '/dashboard/admin/owners',
    adminServices: '/dashboard/admin/services',
    adminServiceTypes: '/dashboard/admin/service-types',
    events: '/dashboard/events',
    activity: '/dashboard/activity',
    appointments: '/dashboard/appointments',
    schedules: '/dashboard/schedules',
    history: '/dashboard/history',
    metrics: '/dashboard/metrics',
    service: '/dashboard/business',
    servicePublicBooking: '/dashboard/business/:serviceId/public-booking',
    unavailability: '/dashboard/unavailability',
    status: '/dashboard/status',
    team: '/dashboard/team',
    account: '/dashboard/account',
    profile: '/dashboard/profile',
    settings: '/dashboard/settings',
    welcome: '/dashboard/welcome',
  },

  service: {
    create: '/service/new',
  },
} as const;
